name: CI - Test and Validate BoxMaker

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test BoxMaker Functionality
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'  # Latest Python version

    - name: Install and cache APT packages
      uses: tecolicom/actions-use-apt-tools@v1
      with:
        tools: libgirepository-2.0-dev gir1.2-glib-2.0 libglib2.0-dev libcairo2-dev gobject-introspection pkg-config python3-dev
        cache: yes

    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install inkex
      run: |
        python -m pip install inkex

    - name: Run test suite
      run: |
        python run_tests.py --ci
